#!/usr/bin/bash -e

SCRIPT_DIR="$(dirname $(realpath $0))"

function _echo {
	echo "[#] ${@}"
}

function _error {
	echo "[!] ${@}"
}


# Add repositories
_echo "Adding repositories"
sudo dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo


# Install packages
_echo "Installing packages"
sudo dnf install -y \
	gh \
	mtr \
	neovim \
	ripgrep \
	qutebrowser \
